#!/bin/bash
name=$1
version=$(curl https://ftp.gnu.org/gnu/$name/ | grep "folder.gif" | grep -v "lang" | tail -n 1 | sed "s/.*href=\"//g" | sed "s/\".*//g")
sourcelink="https://ftp.gnu.org/gnu/$name/$version"
echo $sourcelink
version2=$(curl $sourcelink | grep -v ".sig\"" | grep -v ".sig\"" | grep -v "latest" | grep -v "bin" | grep -v "woe32"  | grep -v "windows" | grep -v "folder.gif" grep "$name-" | tail -n 1 | sed "s/.*href=\"//g" | sed "s/\".*//g")
echo "$sourcelink$version2"
