#!/bin/bash
name=$1
version=$(curl https://ftp.gnu.org/gnu/$name/ | grep "folder.gif" | grep -v "lang" | tail -n 1 | sed "s/.*href=\"//g" | sed "s/\".*//g")
sourcelink="https://ftp.gnu.org/gnu/$name/$version"
version2=$(curl $sourcelink | grep -v ".sig\"" | grep -v "latest" | grep "$name-" | tail -n 1 | sed "s/.*href=\"//g" | sed "s/\".*//g")
echo "$sourcelink$version2"
